name: Docker build
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          #          password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.CR_PAT }}
          image: ${{ github.repository }}:latest
